pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - '#approved-reviews-by>=1'
      - status-success=build
      - status-success=netlify/catchen/deploy-preview
    actions:
      merge:
        method: squash
      delete_head_branch:
