[build]
  command = "yarn build"
  publish = "www"

# singular to plural correction
[[redirects]]
  from = "/service/"
  to = "/services/"
  status = 301
[[redirects]]
  from = "/:locale/service/"
  to = "/:locale/services/"
  status = 301
[[redirects]]
  from = "/project/"
  to = "/projects/"
  status = 301
[[redirects]]
  from = "/:locale/project/"
  to = "/:locale/projects/"
  status = 301
[[redirects]]
  from = "/content/"
  to = "/contents/"
  status = 301
[[redirects]]
  from = "/:locale/content/"
  to = "/:locale/contents/"
  status = 301

# zh locale
[[redirects]]
  from = "/"
  to = "/zh/"
  status = 200
  force = true
  conditions = {Language = ["zh"]}
[[redirects]]
  from = "/resume/"
  to = "/zh/resume/"
  status = 200
  force = false
  conditions = {Language = ["zh"]}
[[redirects]]
  from = "/services/"
  to = "/zh/services/"
  status = 200
  force = false
  conditions = {Language = ["zh"]}
[[redirects]]
  from = "/projects/"
  to = "/zh/projects/"
  status = 200
  force = false
  conditions = {Language = ["zh"]}
[[redirects]]
  from = "/contents/"
  to = "/zh/contents/"
  status = 200
  force = false
  conditions = {Language = ["zh"]}

# en locale
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  force = true
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/resume/"
  to = "/en/resume/"
  status = 200
  force = false
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/services/"
  to = "/en/services/"
  status = 200
  force = false
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/projects/"
  to = "/en/projects/"
  status = 200
  force = false
  conditions = {Language = ["en"]}
[[redirects]]
  from = "/contents/"
  to = "/en/contents/"
  status = 200
  force = false
  conditions = {Language = ["en"]}

# other locales
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  force = true
[[redirects]]
  from = "/resume/"
  to = "/en/resume/"
  status = 200
  force = false
[[redirects]]
  from = "/services/"
  to = "/en/services/"
  status = 200
  force = false
[[redirects]]
  from = "/projects/"
  to = "/en/projects/"
  status = 200
  force = false
[[redirects]]
  from = "/contents/"
  to = "/en/contents/"
  status = 200
  force = false

# v2 legacy path migration
[[redirects]]
  from = "/post/"
  to = "/contents/"
  status = 301
[[redirects]]
  from = "/posts/"
  to = "/contents/"
  status = 301

# v1 to v2 page mappings
[[redirects]]
  from = "/home.en.html"
  to = "/en/"
[[redirects]]
  from = "/cv.en.html"
  to = "/en/resume"
[[redirects]]
  from = "/portfolio.en.html"
  to = "/en/projects"
[[redirects]]
  from = "/more.en.html"
  to = "/en/contents"
[[redirects]]
  from = "/home.zh-CN.html"
  to = "/zh/"
[[redirects]]
  from = "/cv.zh-CN.html"
  to = "/zh/resume"
[[redirects]]
  from = "/portfolio.zh-CN.html"
  to = "/zh/projects"
[[redirects]]
  from = "/more.zh-CN.html"
  to = "/zh/contents"
[[redirects]]
  from = "/home.zh-HK.html"
  to = "/zh/"
[[redirects]]
  from = "/cv.zh-HK.html"
  to = "/zh/resume"
[[redirects]]
  from = "/portfolio.zh-HK.html"
  to = "/zh/projects"
[[redirects]]
  from = "/more.zh-HK.html"
  to = "/zh/contents"

[[redirects]]
  from = "https://catchen.netlify.com/*"
  to = "https://catchen.me/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
