[build]
  command = "npm install -g harp && harp compile"
  publish = "www"

[[redirects]]
  from = "/"
  to = "/zh/"
  status = 302
  force = false
  conditions = {Language = ["zh"]}

[[redirects]]
  from = "/"
  to = "/en/"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
