name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, "[0-9]+-[0-9]+-*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          check-latest: true
      - run: yarn install
      - run: yarn build
